### ISSUE TITLE
Question about ADA 

### ISSUE THREAD

**Issue by Ed-ivan** [Tengfei-Wang/HFGI#10]
Thanks for sharing your code and your excellent work!
While I have a question about  how the ADA work on X_edit ?   I notice that  when training the ADA module , low-fidelity X_o is taken as target image I for alignment ,but there is no X_edit. Thanks for your reply.

**Comment by Tengfei-Wang** [comment]
When training, apply some random augmentation on the low fidelity image to simulate some unaligned inputs, since we do not have ground truth edited images. The ADA model is thus expected to restore the low fidelity image when training.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: jinbh ***@***.***>
发送时间: Saturday, January 14, 2023 5:18:52 PM
收件人: Tengfei-Wang/HFGI ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Tengfei-Wang/HFGI] Question about ADA (Issue #10)


Thanks for sharing your code and your excellent work!
While I have a question about how the ADA work on X_edit ? I notice that when training the ADA module , low-fidelity X_o is taken as target image I for alignment ,but there is no X_edit. Thanks for your reply.

―
