### ISSUE TITLE
Could you provide a FFHQ 256x256 model?

### ISSUE THREAD

**Issue by SleyAI** [Tengfei-Wang/HFGI#12]
Hello, I'm struggling to train a model on the FFHQ 256x256 dataset. I trained an Encoder4Editing model on the entire FFHQ dataset (66k images for training, 4k for validation) and the results look comparable to the ones in the Encoder4Editing paper. Then I trained a HFGI model based on that e4e checkpoint with good results aswell. But when I try to project an image the inversion looks noticeably different than the input image. This problem doesn't appear when I use your pretrained FFHQ 1024x1024 model. I'm assuming that it should be possible to train a 256x256 model with comparable quality.

Could you share a FFHQ 256x256 checkpoint so that I can validate my results? Thank you!

**Comment by Tengfei-Wang** [comment]
Hi,
You can find the checkpoint on faces in our repo. What do your failure results look like? Could you share them?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Henning ***@***.***>
发送时间: Tuesday, March 7, 2023 11:50:13 PM
收件人: Tengfei-Wang/HFGI ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Tengfei-Wang/HFGI] Could you provide a FFHQ 256x256 model? (Issue #12)


Hello, I'm struggling to train a model on the FFHQ 256x256 dataset. I trained an Encoder4Editing model on the entire FFHQ dataset (66k images for training, 4k for validation) and the results look comparable to the ones in the Encoder4Editing paper. Then I trained a HFGI model based on that e4e checkpoint with good results aswell. But when I try to project an image the inversion looks noticeably different than the input image.

Could you share a FFHQ 256x256 checkpoint so that I can validate my results? Thank you!

―

**Comment by SleyAI** [comment]
Hi, thanks. I already found your checkpoint but I believe it's trained to generate 1024x1024 images. 
Currently I'm trying to train a model which generates 256x256 images. Image downscaling from 1024x1024 -> 256x256 is not an option since I want to compare my method (based on HFGI) to another paper which also uses 256x256 images. The 256x256 inversions from the model I trained myself have a noticeable distortion compared to your 1024x1024 model. I attached samples below. First images is input, second is with your checkpoint (1024x1024 downscaled to 256x256) and third is the model trained by me (256x256). 

Generator is the one from Rosinality you provided and e4e model was trained by myself with good sim values (~0.9). With both I trained HFGI by following your description until LPIPS converged against ~0.04.

![223659163-5927d32a-94da-4292-a4fb-0d830180c1da](https://user-images.githubusercontent.com/14246850/223698999-d64b0aff-ff26-4d30-8b24-acf48c1f4112.png)
![223659206-1b638f25-bc86-40e2-a680-ed93b51c51d9](https://user-images.githubusercontent.com/14246850/223699016-80bc6f33-965f-4ad6-965e-f87e8eb898ec.jpg)
![223659221-69ddb0a1-3179-46e4-b234-e96a980ceefb](https://user-images.githubusercontent.com/14246850/223699038-774da3c1-9963-43f0-a318-07983a37bc39.jpg)

**Comment by zpshs** [comment]
Hello, may I ask where the FFHQ 256x256 checkpoint is? I can't find it. thank you.

**Comment by Tengfei-Wang** [comment]
As the pretrained styleGAN we used is of 1024x1024, the resolution of output image is 1024 by default, but the input image can be 256x256.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zpshs ***@***.***>
发送时间: Tuesday, April 18, 2023 10:49:06 AM
收件人: Tengfei-Wang/HFGI ***@***.***>
抄送: Tengfei Wang ***@***.***>; Comment ***@***.***>
主题: Re: [Tengfei-Wang/HFGI] Could you provide a FFHQ 256x256 model? (Issue #12)


Hello, may I ask where the FFHQ 256x256 checkpoint is? I can't find it. thank you.

―
