### ISSUE TITLE
Problem about the results of pose editing

### ISSUE THREAD

**Issue by huiqu18** [Tengfei-Wang/HFGI#2]
Thank you for the great work! I have tried the inference code with the pretrained checkpoint for pose editing, but there are obvious artifacts in the edited images. Could you please double check that the checkpoint is correct? 
BTW, why the pose editing is not included in the inference code or playground notebook?

**Comment by Tengfei-Wang** [comment]
Hi,
May I know whether the editing results on other attributes are correct? Since pose editing suffers larger misalignment than others, we adopt a pre-alignment prior to ADA (as the augmented misalignment in the ADA training does cover largely misaligned cases.)  We have given the details and some failure cases in the supplementary materials, but I am sure whether the current arxiv version includes this part. There are so many files (e.g., images) in the source file, exceeding the limitation of maximum files of arxiv, so I did not upload the full Appendix on it. I am considering putting the compiled appendix on my webpage latter.

**Comment by huiqu18** [comment]
The other editing results are correct. But I didn't find the details about pre-alignment in the Appendix. I am interested in how the pre-alignment is performed as the large pose editing is the most difficult case.
